In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('sales.csv')

In [3]:
df

Region                Country        Item_Type  \
0               Australia and Oceania                 Tuvalu        Baby Food   
1   Central America and the Caribbean                Grenada           Cereal   
2                              Europe                 Russia  Office Supplies   
3                  Sub_Saharan Africa  Sao Tome and Principe           Fruits   
4                  Sub_Saharan Africa                 Rwanda  Office Supplies   
..                                ...                    ...              ...   
95                 Sub_Saharan Africa                   Mali          Clothes   
96                               Asia               Malaysia           Fruits   
97                 Sub_Saharan Africa           Sierra Leone       Vegetables   
98                      North America                 Mexico    Personal Care   
99                 Sub_Saharan Africa             Mozambique        Household   

   Sales_Channel Order_Priority Ship_Date  Unit_Cost  Total_Revenue  \
0        Offline              H  27-06-10     159.42     2533654.00   
1         Online              C  15-09-12     117.11      576782.80   
2        Offline              L  05-08-14     524.96     1158502.59   
3         Online              C  07-05-14       6.92       75591.66   
4        Offline              L  02-06-13     524.96     3296425.02   
..           ...            ...       ...        ...            ...   
95        Online              M  09-03-11      35.84       97040.64   
96       Offline              L  28-12-11       6.92       58471.11   
97       Offline              C  29-06-16      90.93      228779.10   
98       Offline              M  08-08-15      56.67      471336.91   
99       Offline              L  15-02-12     502.54     3586605.09   

    Total_Profit  Unnamed: 9  Unnamed: 10  
0      951410.50         NaN          NaN  
1      248406.36         NaN          NaN  
2      224598.75         NaN          NaN  
3       19525.82         NaN          NaN  
4      639077.50         NaN          NaN  
..           ...         ...          ...  
95      65214.72         NaN          NaN  
96      15103.47         NaN          NaN  
97      93748.05         NaN          NaN  
98     144521.02         NaN          NaN  
99     889472.91         NaN          NaN  

[100 rows x 11 columns]

In [4]:
x=np.array(df["Total_Revenue"]).reshape(-1,1)
y=np.array(df["Total_Profit"]).reshape(-1,1)
x

array([[2.53365400e+06],
       [5.76782800e+05],
       [1.15850259e+06],
       [7.55916600e+04],
       [3.29642502e+06],
       [7.59202720e+05],
       [2.79804649e+06],
       [1.24511292e+06],
       [4.96101100e+05],
       [1.35618010e+06],
       [1.91034400e+04],
       [4.55479040e+05],
       [9.02980640e+05],
       [5.99705498e+06],
       [4.00558730e+05],
       [1.82825440e+05],
       [3.03941440e+06],
       [2.57653500e+05],
       [2.55947410e+06],
       [2.49252612e+06],
       [1.90183600e+06],
       [3.24971440e+05],
       [3.39490500e+05],
       [2.04047100e+04],
       [4.14371100e+05],
       [7.93518000e+05],
       [5.03633400e+04],
       [5.43192600e+04],
       [2.43133800e+05],
       [1.58379990e+06],
       [3.78658920e+06],
       [1.73676250e+05],
       [1.90413804e+06],
       [5.51322750e+06],
       [1.11795366e+06],
       [5.23807570e+05],
       [3.53047200e+04],
       [2.01114963e+06],
       [4.36831668e+06],
       [2.59637427e+06],


In [5]:
y

array([[9.51410500e+05],
       [2.48406360e+05],
       [2.24598750e+05],
       [1.95258200e+04],
       [6.39077500e+05],
       [2.85087640e+05],
       [6.93911510e+05],
       [5.10216660e+05],
       [1.52114200e+05],
       [5.84073870e+05],
       [7.82812000e+03],
       [3.06097920e+05],
       [6.06834720e+05],
       [1.48726102e+06],
       [1.22819060e+05],
       [1.22865120e+05],
       [1.20874424e+06],
       [8.50338000e+04],
       [6.34745900e+05],
       [3.37937600e+05],
       [7.14157000e+05],
       [1.22029780e+05],
       [1.22686500e+05],
       [5.27067000e+03],
       [1.27054200e+05],
       [3.15574050e+05],
       [1.30091800e+04],
       [1.40310200e+04],
       [8.02418400e+04],
       [3.92780100e+05],
       [1.50588807e+06],
       [5.32525000e+04],
       [3.69155000e+05],
       [1.36727250e+06],
       [4.04010780e+05],
       [1.60609540e+05],
       [9.11944000e+03],
       [2.72672400e+05],
       [8.46885000e+05],
       [5.03358750e+05],


In [6]:
x.ndim

2

In [7]:
x_mean=x.mean()
y_mean=y.mean()
x_mean

1373487.6831

In [8]:
y_mean

441681.98399999994

In [13]:
# num=0
# dim=0
# for i in range(len(x)):
#     num+=(x[i]-x_mean)*(y[i]-y_mean)
#     dim+=(x[i]-x_mean)**2
# coff=num/dim
# intr=y_mean-(coff*x_mean)
# print("Intercept value is ",float(intr))
# print("coffi. value is ",float(coff))
# m=coff
# c=intr
# y=m*11+c
# z=m*951410.50+c
# print(y)
# print(z)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model=LinearRegression()

In [19]:
model.fit(x,y)

LinearRegression()

In [20]:
testing=np.array([11,951410,12]).reshape(-1,1)
model.predict(testing)

array([[ 71497.92952284],
       [327922.18745098],
       [ 71498.19904621]])

# Mean Absolute Error

In [21]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
x_test=np.array([[6],[7],[8],[9],[10]])
y_test=np.array([[7],[9],[10],[11],[13]])
x_test

array([[ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [22]:
y_pred=model.predict(x_test)
y_pred

array([[71496.58190603],
       [71496.85142939],
       [71497.12095276],
       [71497.39047612],
       [71497.65999948]])

In [23]:
mse=mean_squared_error(y_test,y_pred)
y_test

array([[ 7],
       [ 9],
       [10],
       [11],
       [13]])

In [24]:
mse

5110408464.749929

In [25]:
rmse=np.sqrt(mean_squared_error(y_test,y_pred))

In [26]:
rmse

71487.12097119263

In [27]:
mean_absolute_error(y_test,y_pred)

71487.12095275607