In [3]:
import pandas as pd
import nltk

In [4]:
df=pd.DataFrame({"Text":["Yellow Green Blue","Blue Yellow Pink","Yellow Green Blue"]})

In [5]:
df

Text
0  Yellow Green Blue
1   Blue Yellow Pink
2  Yellow Green Blue

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
c=CountVectorizer()
x=c.fit_transform(df["Text"])
c.vocabulary_

{'yellow': 3, 'green': 1, 'blue': 0, 'pink': 2}

In [7]:
df.loc[0]

Text    Yellow Green Blue
Name: 0, dtype: object

In [8]:
x[0].toarray()

array([[1, 1, 0, 1]], dtype=int64)

In [9]:
df

Text
0  Yellow Green Blue
1   Blue Yellow Pink
2  Yellow Green Blue

In [10]:
x.toarray()

array([[1, 1, 0, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1]], dtype=int64)

In [11]:
cv=CountVectorizer(ngram_range=(2,2))
x=cv.fit_transform(df["Text"])
cv.vocabulary_

{'yellow green': 2, 'green blue': 1, 'blue yellow': 0, 'yellow pink': 3}

In [12]:
df.loc[0]

Text    Yellow Green Blue
Name: 0, dtype: object

In [13]:
x[0].toarray()

array([[0, 1, 1, 0]], dtype=int64)

In [14]:
df

Text
0  Yellow Green Blue
1   Blue Yellow Pink
2  Yellow Green Blue

In [17]:
cv1=CountVectorizer(ngram_range=(1,3))
x=cv1.fit_transform(df["Text"])
cv1.vocabulary_

{'yellow': 6,
 'green': 3,
 'blue': 0,
 'yellow green': 7,
 'green blue': 4,
 'yellow green blue': 8,
 'pink': 5,
 'blue yellow': 1,
 'yellow pink': 9,
 'blue yellow pink': 2}

In [16]:
df.loc[0]

Text    Yellow Green Blue
Name: 0, dtype: object

In [18]:
x[0].toarray()

array([[1, 0, 0, 1, 1, 0, 1, 1, 1, 0]], dtype=int64)

In [19]:
len(cv1.vocabulary_)

10

In [20]:
x.toarray()

array([[1, 0, 0, 1, 1, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1, 0]], dtype=int64)

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
cv3=CountVectorizer()
x=cv3.fit_transform(df["Text"])
from sklearn.feature_extraction.text import TfidfTransformer
tfidf=TfidfTransformer()
y=tfidf.fit_transform(x)
y

<3x4 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [22]:
y.toarray()

array([[0.52284231, 0.67325467, 0.        , 0.52284231],
       [0.45329466, 0.        , 0.76749457, 0.45329466],
       [0.52284231, 0.67325467, 0.        , 0.52284231]])

In [23]:
df

Text
0  Yellow Green Blue
1   Blue Yellow Pink
2  Yellow Green Blue

In [24]:
cv3.vocabulary_

{'yellow': 3, 'green': 1, 'blue': 0, 'pink': 2}