# Import Library

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
print(a)

[1 2 3 4 5]


In [6]:
list1=[1,2,3,4]

In [7]:
list1

[1, 2, 3, 4]

In [14]:
list2=[1,2,4,5,]

In [15]:
list2

[1, 2, 4, 5]

In [17]:
q=np.array([list1,list2])

In [18]:
q

array([[1, 2, 3, 4],
       [1, 2, 4, 5]])

In [19]:
q.ndim

2

In [20]:
np.concatenate([list1,list2])

array([1, 2, 3, 4, 1, 2, 4, 5])

In [22]:
w=np.array(list1+list2)

In [23]:
w

array([1, 2, 3, 4, 1, 2, 4, 5])

In [24]:
np.where(w==4)

(array([3, 6], dtype=int64),)

In [25]:
np.unique(w)

array([1, 2, 3, 4, 5])

In [26]:
w.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [4],
       [5]])

In [27]:
len(w)

8

In [28]:
w.reshape(2,4)

array([[1, 2, 3, 4],
       [1, 2, 4, 5]])

In [29]:
w.reshape(4,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [4, 5]])

In [30]:
np.isin(w,4)

array([False, False, False,  True, False, False,  True, False])

In [31]:
np.isin(w,4).sum()

2

In [32]:
w.sum()

22

In [33]:
sum(w)

22

In [34]:
w

array([1, 2, 3, 4, 1, 2, 4, 5])

In [35]:
w.max()

5

In [36]:
w.min()

1

In [37]:
w.mean()

2.75

In [38]:
len(np.unique(w))

5

In [40]:
np.sqrt(w)

array([1.        , 1.41421356, 1.73205081, 2.        , 1.        ,
       1.41421356, 2.        , 2.23606798])

In [41]:
w**2

array([ 1,  4,  9, 16,  1,  4, 16, 25])

In [42]:
np.square(w)

array([ 1,  4,  9, 16,  1,  4, 16, 25])

In [43]:
a

array([1, 2, 3, 4, 5])

In [44]:
w

array([1, 2, 3, 4, 1, 2, 4, 5])

In [45]:
r=len(np.unique(w))

In [46]:
r*a

array([ 5, 10, 15, 20, 25])

In [47]:
a=np.array([1,2,3,4,6])

In [48]:
r=np.array([2,3,4,5,1])

In [49]:
a*r

array([ 2,  6, 12, 20,  6])

In [50]:
r

array([2, 3, 4, 5, 1])

In [52]:
r.shape

(5,)

In [54]:
r.dot(a) #dot product

46