# Task 1

In [2]:
# Generating random numbers using NumPy

In [7]:
import numpy as np
from numpy import random

In [9]:
random_number=random.randint(50)
print(random_number)

20


# Task 2

In [10]:
# Generate NumPy array and slicing array

In [11]:
import numpy as np

In [12]:
original_arr=np.array([1,2,3,4,5,6])
print(original_arr)

[1 2 3 4 5 6]


In [13]:
sliced_arr=original_arr[1:4]
print(sliced_arr)

[2 3 4]


# Task 3

In [14]:
# Concatenating 2 NumPy arrays

In [15]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
concatenate_array=np.concatenate((arr1,arr2))
print(concatenate_array)

[1 2 3 4 5 6]


# Task 4

In [16]:
# Sort NumPy array

In [18]:
arr1=np.array([3,4,1,2,5,7,8,5,9])
sorted_array=np.sort(arr1)
print(sorted_array)

[1 2 3 4 5 5 7 8 9]
